/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 12 17:40:15 GMT 2024
 */

package imd;

import org.junit.Test;
import static org.junit.Assert.*;
import imd.Livro;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Livro_ESTest extends Livro_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Livro livro0 = new Livro("r9+", (String) null, 0, 0);
      livro0.removerCopias((-295));
      livro0.emprestar();
      assertEquals(294, livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Livro livro0 = new Livro("", "9M9$(jgpbh$-5G{$", 0, 0);
      livro0.emprestar();
      assertEquals("9M9$(jgpbh$-5G{$", livro0.getAutor());
      assertEquals(0, livro0.getCopiasDisponiveis());
      assertEquals(0, livro0.getPaginas());
      assertEquals("", livro0.getTitulo());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Livro livro0 = new Livro((String) null, (String) null, 2621, 2621);
      livro0.getTitulo();
      assertEquals(2621, livro0.getPaginas());
      assertEquals(2621, livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Livro livro0 = new Livro("O'n>BU62P.?GHu", "O'n>BU62P.?GHu", (-405), 2590);
      livro0.getTitulo();
      assertEquals((-405), livro0.getPaginas());
      assertEquals(2590, livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Livro livro0 = new Livro(": xA+eJ3$w/'-qf[JyK", (String) null, 0, (-356));
      int int0 = livro0.getPaginas();
      assertEquals(0, int0);
      assertEquals((-356), livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Livro livro0 = new Livro("", "", 1450, 1450);
      int int0 = livro0.getPaginas();
      assertEquals(1450, int0);
      assertEquals(1450, livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Livro livro0 = new Livro("r9+", (String) null, 0, 0);
      livro0.devolver();
      int int0 = livro0.getCopiasDisponiveis();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Livro livro0 = new Livro("", "", (-4816), (-4816));
      int int0 = livro0.getCopiasDisponiveis();
      assertEquals((-4816), livro0.getPaginas());
      assertEquals((-4816), int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Livro livro0 = new Livro((String) null, (String) null, 4166, 4166);
      livro0.getAutor();
      assertEquals(4166, livro0.getCopiasDisponiveis());
      assertEquals(4166, livro0.getPaginas());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Livro livro0 = new Livro("", "", (-4816), (-4816));
      livro0.getAutor();
      assertEquals((-4816), livro0.getPaginas());
      assertEquals((-4816), livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Livro livro0 = new Livro("", "", (-2312), (-2312));
      livro0.removerCopias((-2312));
      assertEquals(0, livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Livro livro0 = new Livro("", "", (-2312), (-2312));
      livro0.removerCopias(89);
      assertEquals((-2312), livro0.getPaginas());
      assertEquals((-2312), livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Livro livro0 = new Livro("", "", (-2312), (-2312));
      livro0.emprestar();
      assertEquals((-2312), livro0.getPaginas());
      assertEquals((-2312), livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Livro livro0 = new Livro("O'n>BU62P.?GHu", "O'n>BU62P.?GHu", (-405), 2590);
      livro0.getAutor();
      assertEquals((-405), livro0.getPaginas());
      assertEquals(2590, livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Livro livro0 = new Livro("r9+", (String) null, 0, 0);
      int int0 = livro0.getCopiasDisponiveis();
      assertEquals(0, int0);
      assertEquals(0, livro0.getPaginas());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Livro livro0 = new Livro("", "", (-2312), (-2312));
      livro0.getTitulo();
      assertEquals((-2312), livro0.getCopiasDisponiveis());
      assertEquals((-2312), livro0.getPaginas());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Livro livro0 = new Livro("", "", (-2312), (-2312));
      int int0 = livro0.getPaginas();
      assertEquals((-2312), int0);
      assertEquals((-2312), livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Livro livro0 = new Livro("", "", (-2312), (-2312));
      livro0.adicionarCopias((-1));
      assertEquals((-2313), livro0.getCopiasDisponiveis());
  }
}
