/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 12 17:40:51 GMT 2024
 */

package imd;

import org.junit.Test;
import static org.junit.Assert.*;
import imd.Livro;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Livro_ESTest extends Livro_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Livro livro0 = new Livro("OYYG>h-Y[G~", "", 0, 553);
      livro0.removerCopias((-1389));
      assertEquals(1942, livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Livro livro0 = new Livro("9MD>Ud+A0'cV6e_S", "oAI<o(", (-1), 1);
      livro0.adicionarCopias((-3421));
      livro0.emprestar();
      assertEquals((-3420), livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Livro livro0 = new Livro((String) null, (String) null, (-643), (-643));
      livro0.getTitulo();
      assertEquals((-643), livro0.getPaginas());
      assertEquals((-643), livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Livro livro0 = new Livro("", "", (-558), 0);
      livro0.getTitulo();
      assertEquals((-558), livro0.getPaginas());
      assertEquals(0, livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Livro livro0 = new Livro("OYYG>h-Y[G~", "", 0, 553);
      int int0 = livro0.getPaginas();
      assertEquals("OYYG>h-Y[G~", livro0.getTitulo());
      assertEquals(553, livro0.getCopiasDisponiveis());
      assertEquals(0, int0);
      assertEquals("", livro0.getAutor());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Livro livro0 = new Livro("NNz1T[y86MN", (String) null, 504, 0);
      int int0 = livro0.getPaginas();
      assertEquals(504, int0);
      assertEquals(0, livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Livro livro0 = new Livro("NNz1T[y86MN", (String) null, 504, 0);
      livro0.adicionarCopias(504);
      int int0 = livro0.getCopiasDisponiveis();
      assertEquals(504, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Livro livro0 = new Livro((String) null, (String) null, (-2000), (-2000));
      int int0 = livro0.getCopiasDisponiveis();
      assertEquals((-2000), int0);
      assertEquals((-2000), livro0.getPaginas());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Livro livro0 = new Livro("", (String) null, (-255), (-284));
      String string0 = livro0.getAutor();
      assertEquals((-255), livro0.getPaginas());
      assertNull(string0);
      assertEquals((-284), livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Livro livro0 = new Livro("a-sMJ)NX<SMwM<=]vt8", "", 0, 0);
      String string0 = livro0.getAutor();
      assertEquals(0, livro0.getCopiasDisponiveis());
      assertEquals("", string0);
      assertEquals(0, livro0.getPaginas());
      assertEquals("a-sMJ)NX<SMwM<=]vt8", livro0.getTitulo());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Livro livro0 = new Livro("vqztDl%3", "vqztDl%3", 0, 0);
      livro0.removerCopias(0);
      assertEquals(0, livro0.getPaginas());
      assertEquals(0, livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Livro livro0 = new Livro("OYYG>h-Y[G~", "", 0, 553);
      livro0.emprestar();
      assertEquals(552, livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Livro livro0 = new Livro("vqztDl%3", "vqztDl%3", 0, 0);
      livro0.emprestar();
      assertEquals(0, livro0.getCopiasDisponiveis());
      assertEquals(0, livro0.getPaginas());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Livro livro0 = new Livro("Zc`QA", "tFjzK.0G(c4", (-236), (-236));
      String string0 = livro0.getAutor();
      assertEquals("tFjzK.0G(c4", string0);
      assertEquals((-236), livro0.getPaginas());
      assertEquals((-236), livro0.getCopiasDisponiveis());
      assertEquals("Zc`QA", livro0.getTitulo());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Livro livro0 = new Livro("NNz1T[y86MN", (String) null, 504, 0);
      int int0 = livro0.getCopiasDisponiveis();
      assertEquals(0, int0);
      assertEquals(504, livro0.getPaginas());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Livro livro0 = new Livro("OYYG>h-Y[G~", "", 0, 553);
      String string0 = livro0.getTitulo();
      assertEquals(553, livro0.getCopiasDisponiveis());
      assertEquals(0, livro0.getPaginas());
      assertEquals("OYYG>h-Y[G~", string0);
      assertEquals("", livro0.getAutor());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Livro livro0 = new Livro("OYYG>h-Y[G~", "", 0, 553);
      livro0.devolver();
      assertEquals(554, livro0.getCopiasDisponiveis());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Livro livro0 = new Livro("9MD>Ud+A0'cV6e_S", "oAI<o(", (-1), 1);
      int int0 = livro0.getPaginas();
      assertEquals("9MD>Ud+A0'cV6e_S", livro0.getTitulo());
      assertEquals((-1), int0);
      assertEquals(1, livro0.getCopiasDisponiveis());
      assertEquals("oAI<o(", livro0.getAutor());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Livro livro0 = new Livro("9MD>Ud+A0'cV6e_S", "oAI<o(", (-1), 1);
      livro0.adicionarCopias((-3421));
      livro0.removerCopias(0);
      assertEquals((-3420), livro0.getCopiasDisponiveis());
  }
}
