/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 12 17:26:11 GMT 2024
 */

package imd;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import imd.Biblioteca;
import imd.Livro;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Biblioteca_ESTest extends Biblioteca_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Biblioteca biblioteca0 = new Biblioteca("");
      Livro livro0 = new Livro("", (String) null, 0, 0);
      biblioteca0.adicionarLivro(livro0);
      boolean boolean0 = biblioteca0.verificarDisponibilidade("");
      assertEquals(1, biblioteca0.getQuantidadeLivros());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Biblioteca biblioteca0 = new Biblioteca("imd.Livro");
      biblioteca0.popularBiblioteca();
      Livro livro0 = new Livro("imd.Livro", "jO:|(o", 0, 0);
      biblioteca0.adicionarLivro(livro0);
      biblioteca0.removerLivro(livro0);
      assertEquals(3, biblioteca0.getQuantidadeLivros());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Biblioteca biblioteca0 = new Biblioteca("imd.Livro");
      biblioteca0.popularBiblioteca();
      int int0 = biblioteca0.getQuantidadeLivros();
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Biblioteca biblioteca0 = new Biblioteca((String) null);
      biblioteca0.getNome();
      assertEquals(0, biblioteca0.getQuantidadeLivros());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Biblioteca biblioteca0 = new Biblioteca("");
      biblioteca0.getNome();
      assertEquals(0, biblioteca0.getQuantidadeLivros());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Biblioteca biblioteca0 = new Biblioteca("bZr |'E[Wy>BmKP0");
      Livro livro0 = new Livro("EWvT", (String) null, (-333), (-333));
      biblioteca0.adicionarLivro(livro0);
      biblioteca0.buscarLivroPorTitulo("EWvT");
      assertEquals(1, biblioteca0.getQuantidadeLivros());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Biblioteca biblioteca0 = new Biblioteca("imd.Livro");
      Livro livro0 = new Livro("imd.Livro", "3[N6", 328, 328);
      biblioteca0.adicionarLivro(livro0);
      biblioteca0.buscarLivroPorTitulo("imd.Livro");
      assertEquals(1, biblioteca0.getQuantidadeLivros());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Biblioteca biblioteca0 = new Biblioteca("|b)ZOD&I]o");
      Livro livro0 = new Livro("", "", 0, (-391));
      biblioteca0.adicionarLivro(livro0);
      biblioteca0.buscarLivroPorTitulo("");
      assertEquals(1, biblioteca0.getQuantidadeLivros());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Biblioteca biblioteca0 = new Biblioteca((String) null);
      Livro livro0 = biblioteca0.buscarLivroPorTitulo((String) null);
      biblioteca0.adicionarLivro(livro0);
      // Undeclared exception!
      try { 
        biblioteca0.verificarDisponibilidade("o-MYj\flbTHgpP#& ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("imd.Biblioteca", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Biblioteca biblioteca0 = new Biblioteca("imd.Livro");
      biblioteca0.adicionarLivro((Livro) null);
      // Undeclared exception!
      try { 
        biblioteca0.buscarLivroPorTitulo("imd.Livro");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("imd.Biblioteca", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Biblioteca biblioteca0 = new Biblioteca("imd.Livro");
      Livro livro0 = new Livro("imd.Livro", "jO:|(o", 0, 0);
      biblioteca0.adicionarLivro(livro0);
      biblioteca0.buscarLivroPorTitulo("imd.Livro");
      assertEquals(1, biblioteca0.getQuantidadeLivros());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Biblioteca biblioteca0 = new Biblioteca((String) null);
      biblioteca0.popularBiblioteca();
      biblioteca0.buscarLivroPorTitulo((String) null);
      assertEquals(3, biblioteca0.getQuantidadeLivros());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Biblioteca biblioteca0 = new Biblioteca((String) null);
      biblioteca0.popularBiblioteca();
      boolean boolean0 = biblioteca0.verificarDisponibilidade("1984");
      assertEquals(3, biblioteca0.getQuantidadeLivros());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Biblioteca biblioteca0 = new Biblioteca("y");
      Livro livro0 = new Livro("y", "y", (-181), (-181));
      biblioteca0.adicionarLivro(livro0);
      boolean boolean0 = biblioteca0.verificarDisponibilidade("y");
      assertEquals(1, biblioteca0.getQuantidadeLivros());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Biblioteca biblioteca0 = new Biblioteca("y");
      Livro livro0 = new Livro("y", "y", (-181), (-181));
      biblioteca0.removerLivro(livro0);
      assertEquals(0, biblioteca0.getQuantidadeLivros());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Biblioteca biblioteca0 = new Biblioteca("y");
      biblioteca0.getNome();
      assertEquals(0, biblioteca0.getQuantidadeLivros());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Biblioteca biblioteca0 = new Biblioteca("y");
      biblioteca0.popularBiblioteca();
      boolean boolean0 = biblioteca0.verificarDisponibilidade("y");
      assertEquals(3, biblioteca0.getQuantidadeLivros());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Biblioteca biblioteca0 = new Biblioteca("y");
      int int0 = biblioteca0.getQuantidadeLivros();
      assertEquals(0, int0);
  }
}
